### ISSUE TITLE
synpurge can't purge. Exception thrown

### ISSUE THREAD

**Issue by kubax** [aperezdc/synpurge#26]
Hi,

i'm new to synpurge, but i realy like the idea to delete history of my servers database.

Now i fiddled around a litle bit with the configs, but i can't get it to purge anythin (reindex works) here is the traceback i get everytime:

```
Traceback (most recent call last):
  File "/usr/bin/synpurge", line 11, in <module>
    load_entry_point('synpurge==4', 'console_scripts', 'synpurge')()
  File "/usr/lib/python3.7/site-packages/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 370, in __call__
    return self._dispatch()
  File "/usr/lib/python3.7/site-packages/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 382, in _dispatch
    dispatch(parser)
  File "/usr/lib/python3.7/site-packages/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.7/site-packages/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.7/site-packages/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/usr/lib/python3.7/site-packages/synpurge-4-py3.7.egg/synpurge/cli.py", line 175, in purge
    purges, warnings = purger.resolve_room_ids(c, pgdb or api, True)
  File "/usr/lib/python3.7/site-packages/synpurge-4-py3.7.egg/synpurge/purger.py", line 110, in resolve_room_ids
    resolver.resolve(room_conf, replace)
  File "/usr/lib/python3.7/site-packages/synpurge-4-py3.7.egg/synpurge/purger.py", line 95, in resolve
    self.__add(room_conf.name, room_conf, replace)
  File "/usr/lib/python3.7/site-packages/synpurge-4-py3.7.egg/synpurge/purger.py", line 83, in __add
    matched_alias=matched_alias)
  File "<attrs generated init 6e5e2380fc6e3fc75349740cb7bf4fdcbed6109f>", line 10, in __init__
  File "/usr/lib/python3.7/site-packages/attrs-18.2.0-py3.7.egg/attr/validators.py", line 106, in __call__
    self.validator(inst, attr, value)
  File "/usr/lib/python3.7/site-packages/attrs-18.2.0-py3.7.egg/attr/validators.py", line 32, in __call__
    value,
TypeError: ("'matched_alias' must be <class 'str'> (got True that is a <class 'bool'>).", Attribute(name='matched_alias', default=None, validator=<optional validator for <instance_of validator for type <class 'str'>> or None>, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False), <class 'str'>, True)
```

Any ideas what could be wrong?

I'm running Arch Linux with python 3.7

**Comment by rubo77** [comment]
How did you install this?

Maybe you can help here
https://github.com/aperezdc/synpurge/issues/7#issuecomment-412187863
