### ISSUE TITLE
Write documentation / manual

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/synpurge#7]
Currently the only documentation is that provided by launching the program with `--help`, and the comments in the example configuration file. It would be great to have some more documentation.

**Comment by rubo77** [comment]
How do I install this?

I cloned the repository and then tried

    python setup.py

but this only gives lots of errors:

```

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    version=get_version(),
  File "setup.py", line 25, in get_version
    for line in distrib_file("synpurge", "__init__.py"):
  File "setup.py", line 16, in distrib_file
    encoding="utf-8")
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by kubax** [comment]
In my case this problem occurs when explicitly calling it with python2.

So i assume you are using python2 on your system.. try with python3.

Commands i used were

```
python setup.py build
python setup.py install
```
